name: Run Python Tests
on:
  push:
    branches:
      - master
      - tests
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Python 3
        run: |
          sudo apt-get install python3
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install pytest
          pip install -r requirements.txt
      - name: Run tests with pytest
        run: |
          pytest 
